create table if not exists public.tmdb_backfill_jobs (
  id bigint generated by default as identity primary key,
  job_key text not null unique,
  status text not null default 'active' check (status in ('active', 'complete', 'paused', 'failed')),
  start_year integer not null,
  end_year integer not null,
  current_year integer not null,
  next_page integer not null default 1,
  page_count integer not null default 5,
  last_total_pages integer,
  last_run_at timestamptz,
  completed_at timestamptz,
  last_result jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tmdb_backfill_jobs_status_idx
  on public.tmdb_backfill_jobs (status, id);

alter table public.tmdb_backfill_jobs enable row level security;
